from sqlalchemy.orm import Session
from app.modules.users import service as user_service
import uuid
import logging
from datetime import datetime, timedelta

logger = logging.getLogger("ctech_api.auth")

# TODO: In production, store reset tokens in database with expiration
# This in-memory implementation is suitable only for development/single-instance deployments
_reset_tokens: dict[str, dict] = {}  # Format: {token: {"email": str, "expires": datetime}}


def authenticate(db: Session, email: str, password: str):
    """
    Authenticate user with email and password.
    
    Args:
        db: Database session
        email: User email
        password: User password
        
    Returns:
        User object if authentication succeeds, None otherwise
    """
    return user_service.authenticate_user(db, email, password)


def forgot_password(db: Session, email: str) -> bool:
    """
    Process forgot password request.
    
    Args:
        db: Database session
        email: User email
        
    Returns:
        True if email exists and token is generated, False otherwise
        
    Note:
        In production, this should send an email with the reset link.
        Token is stored with 1-hour expiration.
    """
    user = user_service.get_user_by_email(db, email)
    if not user:
        logger.warning(f"Forgot password request for non-existent email: {email}")
        return False
    
    # Generate reset token
    reset_token = str(uuid.uuid4())
    expiration_time = datetime.utcnow() + timedelta(hours=1)
    
    _reset_tokens[reset_token] = {
        "email": email,
        "expires": expiration_time
    }
    
    logger.info(f"Password reset token generated for email: {email}")
    
    # TODO: Send email with reset link containing the token
    # For now, just log it (development only)
    logger.debug(f"Reset token: {reset_token} (expires at {expiration_time})")
    
    return True


def reset_password(db: Session, token: str, new_password: str) -> bool:
    """
    Reset user password using reset token.
    
    Args:
        db: Database session
        token: Reset token generated by forgot_password
        new_password: New password for user
        
    Returns:
        True if password reset successful, False otherwise
        
    Raises:
        ValueError: If password is invalid
    """
    if not token or token not in _reset_tokens:
        logger.warning(f"Reset password attempt with invalid token")
        return False
    
    token_data = _reset_tokens[token]
    
    # Check if token is expired
    if datetime.utcnow() > token_data["expires"]:
        logger.warning(f"Reset password attempt with expired token for: {token_data['email']}")
        del _reset_tokens[token]
        return False
    
    email = token_data["email"]
    user = user_service.get_user_by_email(db, email)
    
    if not user:
        logger.error(f"User not found during password reset: {email}")
        return False
    
    try:
        # HashPassword and update
        from app.core.security import get_password_hash
        from app.modules.users.repository import update_user
        
        hashed_password = get_password_hash(new_password)
        update_user(db, user.id, {"password_hash": hashed_password})
        
        # Invalidate token
        del _reset_tokens[token]
        
        logger.info(f"Password reset successful for user: {email}")
        return True
        
    except Exception as e:
        logger.error(f"Error during password reset: {str(e)}")
        return False

